name: Analytics Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'services/analytics-service/**'
      - 'infrastructure/github-actions/analytics-service.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/analytics-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'services/analytics-service/package-lock.json'

    - name: Install dependencies
      run: |
        cd services/analytics-service
        npm ci

    - name: Lint
      run: |
        cd services/analytics-service
        npm run lint

    - name: Build
      run: |
        cd services/analytics-service
        npm run build

    - name: Test
      run: |
        cd services/analytics-service
        npm test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      if: github.event_name != 'pull_request'

    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      if: github.event_name != 'pull_request'
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      if: github.event_name != 'pull_request'
      with:
        context: ./services/analytics-service
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/analytics-service:${{ github.sha }},${{ secrets.ACR_LOGIN_SERVER }}/analytics-service:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      if: github.event_name != 'pull_request'
      with:
        version: 'latest'

    - name: Set up kubeconfig
      uses: azure/k8s-set-context@v3
      if: github.event_name != 'pull_request'
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy to Kubernetes
      if: github.event_name != 'pull_request'
      run: |
        cd infrastructure/kubernetes
        sed -i "s|IMAGE_TAG|${{ github.sha }}|g" analytics-service.yaml
        kubectl apply -f analytics-service.yaml
