apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurement-service
  labels:
    app: procurement-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: procurement-service
  template:
    metadata:
      labels:
        app: procurement-service
    spec:
      containers:
      - name: procurement-service
        image: ${ACR_LOGIN_SERVER}/procurement-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: supply-stream-secrets
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: supply-stream-secrets
              key: db-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: supply-stream-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: supply-stream-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: supply-stream-secrets
              key: db-name
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: supply-stream-secrets
              key: jwt-secret
        - name: AZURE_SERVICEBUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: supply-stream-secrets
              key: servicebus-connection-string
        - name: AZURE_SERVICEBUS_QUEUE_NAME
          value: "events"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: supply-stream-secrets
              key: sentry-dsn
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: procurement-service
spec:
  selector:
    app: procurement-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
